apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "directus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "directus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          volumeMounts:
            - name: directus-data
              mountPath: /directus/uploads
            {{- if .Values.directusExtensions }}
            - name: extensions-config
              mountPath: "/etc/extensions-config"
              readOnly: true
            {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: directus-env-secrets
                  key: DIRECTUS_KEY
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: directus-env-secrets
                  key: DIRECTUS_SECRET
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: directus-env-secrets
                  key: DIRECTUS_DATABASE_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: directus-env-secrets
                  key: DIRECTUS_DATABASE_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: directus-env-secrets
                  key: DIRECTUS_DATABASE_PASSWORD
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: directus-env-secrets
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: directus-env-secrets
                  key: ADMIN_PASSWORD
            - name: DIRECTUS_INSTALL_TITLE
              valueFrom:
                configMapKeyRef:
                  name: directus-env-configmap
                  key: DIRECTUS_INSTALL_TITLE
            - name: DB_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: directus-env-configmap
                  key: DIRECTUS_DATABASE_CLIENT
            - name: DB_HOST
              value: {{ include "directus.databaseService" . }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: directus-env-configmap
                  key: DIRECTUS_DATABASE_PORT
            {{- if .Values.extraEnvVars }}
            {{- include "directus.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.directusExtensions }}
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - test -f /etc/extensions-config/extensions.yaml && npx -y directus-extensions-installer install --config /etc/extensions-config/extensions.yaml --download-dir /tmp/extension-downloads --directus-dir /directus;
          {{- end }}
          {{- if .Values.command }}
          command:
            {{ .Values.command | toYaml | nindent 12 }} 
          {{- else }}
          command:
            ['sh', '-c']
          {{- end }}

          {{- if .Values.args }}
          args:
            {{ .Values.args | toYaml | nindent 12 }} 
          {{- else }}
          args:
            ['npx directus bootstrap && npx directus start']
          {{- end }}
      volumes:
        - name: directus-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "directus.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{ end }}
        {{- if .Values.directusExtensions }}
        - name: extensions-config
          secret:
            secretName: directus-extensions-secrets
            items:
              - key: extensions
                path: extensions.yaml
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
