{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "directus.fullname" . }}
  labels: {{- include "directus.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "directus.storageClass" . }}
{{- end }}