apiVersion: v1
kind: Secret
metadata:
  name: directus-env-secrets
type: Opaque
data:
  DIRECTUS_KEY:  {{ .Values.directusKey | b64enc }}
  DIRECTUS_SECRET:  {{ .Values.directusSecret | b64enc }}
  DIRECTUS_DATABASE_USER: {{ .Values.directusDatabaseUsername | b64enc }}
  DIRECTUS_DATABASE_NAME: {{ .Values.directusDatabaseName | b64enc }}
  DIRECTUS_DATABASE_PASSWORD: {{ .Values.directusDatabasePassword | b64enc }}
  ADMIN_EMAIL: {{ .Values.directusEmail | b64enc }}
  ADMIN_PASSWORD: {{ .Values.directusPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: directus-extensions-secrets
data:
{{- if .Values.directusExtensions }}
  extensions: |
{{ .Values.directusExtensions | toYaml | b64enc | indent 4 }}
{{- end }}